// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz7AKXfpli3npTddAUWyAxTxnd_rGWttU',
    appId: '1:530708978028:web:6416f1a8d7a64c1aba3b49',
    messagingSenderId: '530708978028',
    projectId: 'my-library-7cb8e',
    authDomain: 'my-library-7cb8e.firebaseapp.com',
    storageBucket: 'my-library-7cb8e.firebasestorage.app',
    measurementId: 'G-ZTE0W70RNV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARdBXdQcLR2If7SzheoDjWjuMGbXTvlVU',
    appId: '1:530708978028:android:92fae3eacdccbc43ba3b49',
    messagingSenderId: '530708978028',
    projectId: 'my-library-7cb8e',
    storageBucket: 'my-library-7cb8e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7qQXcDvNtm-ifj-3YRjlUdCNB4afNQYM',
    appId: '1:530708978028:ios:e6482abae00418a9ba3b49',
    messagingSenderId: '530708978028',
    projectId: 'my-library-7cb8e',
    storageBucket: 'my-library-7cb8e.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7qQXcDvNtm-ifj-3YRjlUdCNB4afNQYM',
    appId: '1:530708978028:ios:e6482abae00418a9ba3b49',
    messagingSenderId: '530708978028',
    projectId: 'my-library-7cb8e',
    storageBucket: 'my-library-7cb8e.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAz7AKXfpli3npTddAUWyAxTxnd_rGWttU',
    appId: '1:530708978028:web:a16e5edb2587d3c9ba3b49',
    messagingSenderId: '530708978028',
    projectId: 'my-library-7cb8e',
    authDomain: 'my-library-7cb8e.firebaseapp.com',
    storageBucket: 'my-library-7cb8e.firebasestorage.app',
    measurementId: 'G-GTMB1B2TT9',
  );
}
